"""Make artwork by hand in ChatGPT: export the prompt list, then import the images.

ChatGPT plans do not include API access, so this is the manual route:

    python3 pipeline/chatgpt_art.py export
        Writes data/artwork-prompts.md (numbered prompts, one copyable block each,
        most-connected nodes first) and data/artwork-prompts.csv.

    python3 pipeline/chatgpt_art.py import ~/Downloads/war-art [--dry-run]
        Paste a prompt into ChatGPT, download the image, and save it in that folder
        named by its list number or node id: "007.png", "7.png", "cleon.png" or
        "007 cleon.png" all work (.png/.jpg/.jpeg/.webp). Each image is centre-cropped
        to a square, resized to 768 px, saved as public/art/<id>.jpg and recorded in
        data/artwork.json as "ChatGPT Image" with the prompt it was made from.
        Run it as often as you like; newer files replace older ones.

The prompts come from artwork.py, so the only node-specific text in them is the
node's Wikipedia title and short description.
"""
import argparse
import csv
import json
import os
import re
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(__file__))
from artwork import ROOT, prompt_for  # noqa: E402

MODEL = "ChatGPT Image"
PROMPTS_MD = os.path.join(ROOT, "data", "artwork-prompts.md")
PROMPTS_CSV = os.path.join(ROOT, "data", "artwork-prompts.csv")
ART_JSON = os.path.join(ROOT, "data", "artwork.json")
EXTS = (".png", ".jpg", ".jpeg", ".webp")


def prompt_list():
    """Nodes without a public-domain image, most-connected first, numbered from 1."""
    g = json.load(open(os.path.join(ROOT, "data", "graph.raw.json")))
    degree = Counter()
    for e in g["edges"]:
        degree[e["source"]] += 1
        degree[e["target"]] += 1
    nodes = sorted((n for n in g["nodes"] if not n.get("img")), key=lambda n: (-degree[n["id"]], n["id"]))
    return [dict(num=i, id=n["id"], type=n["type"], title=n["title"], prompt=prompt_for(n))
            for i, n in enumerate(nodes, 1)]


def export(_args):
    rows = prompt_list()
    with open(PROMPTS_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["num", "id", "type", "title", "prompt"])
        w.writeheader()
        w.writerows(rows)
    lines = [
        "# Artwork prompts for ChatGPT",
        "",
        f"{len(rows)} nodes without a public-domain image, most-connected first. "
        "Generated by `python3 pipeline/chatgpt_art.py export`; do not edit by hand.",
        "",
        "For each one: copy the prompt into ChatGPT (ask for a **square** image), download the result, "
        "and save it as the file name shown, e.g. `007.png`, in one folder. Then run "
        "`python3 pipeline/chatgpt_art.py import <folder>`.",
        "",
    ]
    for r in rows:
        lines += [f"## {r['num']:03d} · {r['title']}", "",
                  f"Save as `{r['num']:03d}.png` · node `{r['id']}` · {r['type']}", "",
                  "```text", r["prompt"], "```", ""]
    open(PROMPTS_MD, "w").write("\n".join(lines))
    print(f"wrote {len(rows)} prompts to data/artwork-prompts.md and data/artwork-prompts.csv")


def match(filename, by_num, by_id):
    stem = os.path.splitext(filename)[0].strip().lower()
    if stem in by_id:
        return by_id[stem]
    m = re.match(r"(\d+)\b[\s._-]*(.*)$", stem)
    if not m:
        return None
    row = by_num.get(int(m.group(1)))
    rest = m.group(2).strip()
    if row and rest in by_id and by_id[rest] is not row:
        print(f"skipped {filename}: number {row['num']:03d} is {row['id']}, not {rest}")
        return False  # number and id disagree: better to skip than to guess
    return row


def import_(args):
    from PIL import Image, ImageOps

    rows = prompt_list()
    by_num = {r["num"]: r for r in rows}
    by_id = {r["id"]: r for r in rows}
    files = sorted(f for f in os.listdir(args.folder) if f.lower().endswith(EXTS))
    picked, unmatched = {}, []
    for f in files:
        row = match(f, by_num, by_id)
        if not row:
            if row is None:
                unmatched.append(f)
            continue
        path = os.path.join(args.folder, f)
        prev = picked.get(row["id"])
        if not prev or os.path.getmtime(path) > os.path.getmtime(prev):
            picked[row["id"]] = path

    done = {a["node_id"]: a for a in json.load(open(ART_JSON))} if os.path.exists(ART_JSON) else {}
    os.makedirs(os.path.join(ROOT, "public", "art"), exist_ok=True)
    for node_id, path in sorted(picked.items(), key=lambda kv: by_id[kv[0]]["num"]):
        row = by_id[node_id]
        print(f"{row['num']:03d} {node_id} <- {os.path.basename(path)}")
        if args.dry_run:
            continue
        im = ImageOps.exif_transpose(Image.open(path)).convert("RGB")
        im = ImageOps.fit(im, (768, 768), Image.LANCZOS)
        im.save(os.path.join(ROOT, "public", "art", f"{node_id}.jpg"), quality=86, optimize=True)
        done[node_id] = dict(node_id=node_id, url=f"/art/{node_id}.jpg", model=MODEL, prompt=row["prompt"])
    if not args.dry_run and picked:
        json.dump(list(done.values()), open(ART_JSON, "w"), indent=1)

    for f in unmatched:
        print(f"skipped {f}: name it by list number or node id")
    ours = sum(1 for r in rows if done.get(r["id"], {}).get("model") == MODEL)
    verb = "would import" if args.dry_run else "imported"
    print(f"{verb} {len(picked)}; {ours} of {len(rows)} nodes now have ChatGPT artwork")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("export", help="write data/artwork-prompts.md and .csv").set_defaults(fn=export)
    p = sub.add_parser("import", help="import downloaded ChatGPT images from a folder")
    p.add_argument("folder")
    p.add_argument("--dry-run", action="store_true", help="show what would be imported without writing")
    p.set_defaults(fn=import_)
    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
