import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 3, ignoreHTTPSErrors: true });
await p.goto((process.env.BASE_URL || "http://localhost:4173") + "/#graph");
await p.waitForFunction(() => window.__app?.model?.nodes?.length > 0, null, { timeout: 60000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: "qa/screenshots/20-mobile-intro.png" });
const r = await p.evaluate(() => { const b = document.querySelector("#intro-go").getBoundingClientRect(); return [Math.round(b.top), Math.round(b.bottom), innerHeight]; });
await p.click("#intro-go", { timeout: 8000 });
await p.waitForTimeout(800);
console.log("intro-go box", r, "dismissed:", await p.evaluate(() => document.body.classList.contains("intro-done")));
await b.close();
